version: '3.9'

services:
  api:
    image: crud-drf:1.0.0
    container_name: crud-drf-container
    build: .
    entrypoint: "python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - drf-ntw
  db:
    image: mysql-db:1.0.0
    container_name: mysql-db-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - drf-ntw
  
volumes:
  mysql_data:

networks:
  drf-ntw:
    driver: bridge